# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSReader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='rss',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
