# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSReader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='upsidedown',
            field=models.BooleanField(default=False),
        ),
    ]
