# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSReader', '0003_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='texto',
            field=models.CharField(max_length=1000),
        ),
    ]
