# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSSReader', '0004_auto_20170217_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feed',
            new_name='Entrada',
        ),
    ]
